name: build

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-18.04
  
    steps:
    - uses: actions/checkout@v2
    - name: Setup golang
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.2'
    - name: Setup gomobile
      run: |
        go get golang.org/x/mobile/cmd/gomobile
        gomobile init -v
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Data
      uses: actions/cache@v1
      env:
        ndk: android-ndk-r20b
        sdk-tools: 4333796
      with:
        path: ~/.android-cache
        key: ${{ runner.os }}-android-${{ env.ndk-version }}-${{ env.sdk-tools }}
        restore-keys: |
          ${{ runner.os }}-android-${{ env.ndk-version }}-${{ env.sdk-tools }}           
    - name: Setup Android
      run: |
        wget "https://raw.githubusercontent.com/xxf098/shadowsocksr-v2ray-android/e11d00241361ee400f1a9f77df3d8d3f975c9652/travis-ci/setup.sh" -O setup.sh
        sed -i 's/r12b/r20b/g' setup.sh && chmod +x setup.sh
        ./setup.sh
    - name: Check Build
      run: |
        go version
        java -version
